
TEMP_LOCAL_PATH :=$(call my-dir)/..

include $(TEMP_LOCAL_PATH)/../mk_template/flags.mk
include $(LOCAL_PATH)/../../mk_template/util.mk

LOCAL_CFLAGS += -fvisibility=hidden
LOCAL_CFLAGS += -Wno-error=maybe-uninitialized  # x86 compile: ini.h
LOCAL_CFLAGS := $(LOCAL_CFLAGS:-Wconversion=)

SRC := $(wildcard $(TEMP_LOCAL_PATH)/jni/*.cc)
SRC := $(SRC:$(LOCAL_PATH)/%=%)
LOCAL_SRC_FILES += $(SRC)

SRC := $(wildcard $(TEMP_LOCAL_PATH)/src/*.cc)
SRC := $(SRC:$(LOCAL_PATH)/%=%)
LOCAL_SRC_FILES += $(SRC)

SRC := $(wildcard $(TEMP_LOCAL_PATH)/src/*.c)
SRC := $(SRC:$(LOCAL_PATH)/%=%)
LOCAL_SRC_FILES += $(SRC)

SRC := $(wildcard $(TEMP_LOCAL_PATH)/src/Proto/*.cc)
SRC := $(SRC:$(LOCAL_PATH)/%=%)
LOCAL_SRC_FILES += $(SRC)

SRC := $(wildcard $(TEMP_LOCAL_PATH)/src/Proto/pbc/*.c)
SRC := $(SRC:$(LOCAL_PATH)/%=%)
LOCAL_SRC_FILES += $(SRC)


SRC := $(wildcard $(TEMP_LOCAL_PATH)/*.cc)
SRC := $(SRC:$(LOCAL_PATH)/%=%)
LOCAL_SRC_FILES += $(SRC)

LOCAL_CFLAGS += -I$(TEMP_LOCAL_PATH)/src/Proto/protobuf/src/
LOCAL_CPPFLAGS += -std=c++11

LOCAL_CFLAGS +=  -DSQLITE_HAS_CODEC -DHAVE_USLEEP=1 -DSQLITE_SOUNDEX -DSQLITE_MAX_VARIABLE_NUMBER=99999 -DSQLITE_TEMP_STORE=3 -DSQLITE_THREADSAFE=1 -DSQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=1048576 -DNDEBUG=1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_ENABLE_DBSTAT_VTAB

LOCAL_C_INCLUDES += $(TEMP_LOCAL_PATH)/ $(TEMP_LOCAL_PATH)/src $(TEMP_LOCAL_PATH)/../../
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../3rd/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../openssl/include
